version: '3'

services:
  frontend:
    container_name: chatbot-frontend
    build: ./backend
    pull_policy: build
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 10.11.2.15
  backend:
    container_name: chatbot-backend
    build: ./backend
    pull_policy: build
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      lan:
        ipv4_address: 10.11.2.14

networks:
  lan:
    name: LAN
    external: true